from cosmic import expand, find_galaxies, all_pairs

input_str = """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#....."""
expanded_str = """....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#......."""


def test_expand():
    input_grid = [list(i.strip()) for i in input_str.split("\n")]
    result = expand(input_grid)

    expected_grid = [list(i.strip()) for i in expanded_str.split("\n")]
    assert result == expected_grid

def test_total():
    expanded_grid = [list(i.strip()) for i in expanded_str.split("\n")]
    galaxies = find_galaxies(expanded_grid)
    result = all_pairs(galaxies)
    assert result == 374




